cmake_minimum_required(VERSION 3.16)
project(PetrichorEngine LANGUAGES C CXX)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_subdirectory(PetrichorBackends/PetrichorInputAPI)
add_subdirectory(PetrichorBackends/PetrichorRendererAPI)
add_subdirectory(PetrichorBackends/SDL3_OpenGL_Backend)

add_subdirectory(PetrichorEngine)

add_subdirectory(PetrichorEditor)