
#define STB_IMAGE_IMPLEMENTATION
#include <glm/glm.hpp>
#include <SDL3/SDL.h>
#include <SDL3/SDL_keycode.h>
#include <algorithm>
#include <glm/ext/matrix_transform.hpp>
#include <glm/fwd.hpp>
#include <glm/geometric.hpp>
#include <glm/trigonometric.hpp>
#include <map>
#include <string>
#include <utility>
#include <glad/glad.h>
#include <GL/gl.h>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

#include "ptc_camera.hpp"
#include "ptc_component.hpp"
#include "ptc_console.hpp"
#include "ptc_debug.hpp"
#include "ptc_face_token.hpp"
#include "ptc_file_processor.hpp"
#include "ptc_font.hpp"
#include "ptc_gui_structs.hpp"
#include "ptc_gui.hpp"
#include "ptc_input.hpp"
#include "ptc_json_structs.hpp"
#include "ptc_json.hpp"
#include "ptc_light.hpp"
#include "ptc_material.hpp"
#include "ptc_math.hpp"
#include "ptc_mesh_filter.hpp"
#include "ptc_mesh_loader.hpp"
#include "ptc_mesh_renderer.hpp"
#include "ptc_mesh.hpp"
#include "ptc_object.hpp"
#include "ptc_renderer.hpp"
#include "ptc_shader.hpp"
#include "ptc_state.hpp"
#include "ptc_text.hpp"
#include "ptc_texture.hpp"
#include "ptc_time.hpp"
#include "ptc_transform.hpp"
#include "ptc_vertex.hpp"